name: Manual CI/CD Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose deployment environment"
        required: true
        type: choice
        default: dev
        options:
          - dev
          - staging
          - prod

      namespace:
        description: "Kubernetes namespace"
        required: true
        type: choice
        default: sock-shop
        options:
          - sock-shop
          - habiba-dev
          - cloudnova

      action:
        description: "What do you want to run?"
        required: true
        type: choice
        default: deploy
        options:
          - plan
          - deploy
          - destroy

      apply_terraform:
        description: "Run Terraform?"
        required: true
        type: boolean
        default: false

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: sock-shop-${{ inputs.environment }}-eks

jobs:
  manual-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show selected parameters
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Namespace: ${{ inputs.namespace }}"
          echo "Action: ${{ inputs.action }}"
          echo "Apply Terraform: ${{ inputs.apply_terraform }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        if: ${{ inputs.action == 'plan' || inputs.action == 'destroy' || inputs.apply_terraform == true }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Plan
        if: ${{ inputs.action == 'plan' || inputs.apply_terraform == true }}
        run: |
          cd terraform/eks
          terraform init
          terraform plan

      - name: Update kubeconfig for EKS
        if: ${{ inputs.action == 'deploy' }}
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy Kubernetes manifests
        if: ${{ inputs.action == 'deploy' }}
        run: |
          echo "Deploying to namespace: ${{ inputs.namespace }}"
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/ -n ${{ inputs.namespace }}

      - name: Destroy Terraform
        if: ${{ inputs.action == 'destroy' }}
        run: |
          cd terraform/eks
          terraform init
          terraform destroy -auto-approve

      - name: Complete job
        run: echo "Job completed successfully"
